trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  steps:

  - checkout: self

  - task: Docker@2
    displayName: 'Build and Push Docker image'
    inputs:
      containerRegistry: 'dh-con' # You may need to set up a DockerHub service connection in your Azure DevOps project
      repository: 'cloudwithraghu/app'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: 'latest'
